services:
  postgres-db:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-email
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: always
    volumes:
      - ./dados:/var/lib/rabbitmq/

  ms-eureka:
    hostname: eureka
    image: eureka-api
    build:
      context: ./eureka
      dockerfile: Dockerfile

  ms-gateway:
    hostname: gateway
    image: gateway-api
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - ms-eureka

  ms-notification:
    hostname: notification
    image: notification-api
    build:
      context: ./notification
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
      - rabbitmq
      - ms-eureka

  ms-project:
    hostname: project
    image: project-api
    build:
      context: ./project
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
      - ms-eureka

  ms-security:
    hostname: security
    image: security-api
    build:
      context: ./security
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
      - ms-eureka

volumes:
  postgres-data:

